# Generated by Django 4.1.7 on 2023-03-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=300)),
                ('release', models.DateField()),
                ('lte_exists', models.CharField(default='-', max_length=6)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
